# Generated by Django 4.1 on 2022-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
