# Generated by Django 4.1 on 2022-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='learn',
            field=models.BooleanField(default=False),
        ),
    ]
