# Generated by Django 4.1 on 2022-08-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='gp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='words.group'),
            preserve_default=False,
        ),
    ]
