# Generated by Django 4.1 on 2022-08-27 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_remove_group_words_word_gp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='learn',
        ),
        migrations.AddField(
            model_name='word',
            name='cycle',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
