# Generated by Django 4.1 on 2022-08-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_remove_word_learn_word_cycle_alter_group_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='cycle',
        ),
    ]
