# Generated by Django 4.1 on 2022-08-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='special_user',
        ),
        migrations.AddField(
            model_name='user',
            name='leitner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='leitner.leitner'),
            preserve_default=False,
        ),
    ]
