# Generated by Django 4.1 on 2022-08-30 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0009_remove_word_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.DateTimeField(default=django.utils.timezone.now)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lword', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Leitner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d1', to='leitner.lword')),
                ('d2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d2', to='leitner.lword')),
                ('d3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d3', to='leitner.lword')),
                ('m1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m1', to='leitner.lword')),
                ('m2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2', to='leitner.lword')),
                ('w1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w1', to='leitner.lword')),
                ('w2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w2', to='leitner.lword')),
            ],
        ),
    ]
