# Generated by Django 4.1 on 2022-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0002_remove_leitner_d1_remove_leitner_d2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitner',
            name='d1',
        ),
        migrations.RemoveField(
            model_name='leitner',
            name='d2',
        ),
        migrations.RemoveField(
            model_name='leitner',
            name='d3',
        ),
        migrations.RemoveField(
            model_name='leitner',
            name='m1',
        ),
        migrations.RemoveField(
            model_name='leitner',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='leitner',
            name='w1',
        ),
        migrations.RemoveField(
            model_name='leitner',
            name='w2',
        ),
        migrations.AddField(
            model_name='leitner',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lword',
            name='status',
            field=models.CharField(choices=[('d1', 'روز اول'), ('d2', 'روز دوم'), ('d3', 'روز سوم'), ('w1', 'هفته اول'), ('w2', 'هفته دوم'), ('m1', 'ماه اول'), ('m2', 'ماه دوم')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
