# Generated by Django 4.1 on 2022-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0003_remove_leitner_d1_remove_leitner_d2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lword',
            name='status',
            field=models.CharField(choices=[('1', 'd1'), ('2', 'd2'), ('3', 'd3'), ('4', 'w1'), ('5', 'w2'), ('6', 'm1'), ('7', 'm2')], max_length=1),
        ),
    ]
