# Generated by Django 4.1 on 2022-08-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0004_alter_lword_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lword',
            name='leitner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lword', to='leitner.leitner'),
            preserve_default=False,
        ),
    ]
