# Generated by Django 4.1 on 2022-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitner', '0005_lword_leitner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lword',
            name='status',
            field=models.CharField(choices=[('1', 'd1'), ('2', 'd2'), ('3', 'd3'), ('4', 'w1'), ('5', 'w2'), ('6', 'm1'), ('7', 'm2')], default='1', max_length=1),
        ),
    ]
